/**
 * `allman companies` — resolve the employers behind stored work history.
 *
 * Every position carries a `companyUrn`, so the firm itself can be looked up
 * directly instead of guessing a domain from the company name. That is the
 * difference between knowing a company's real website and headcount band and
 * inferring them from a string.
 *
 *   allman companies                 resolve every unresolved employer
 *   allman companies --current-only  only people's current employers
 *   allman companies --limit 200     cap how many to fetch this run
 *   allman companies --force         re-fetch companies already stored
 *   allman companies <urn|id|slug>   resolve a single company
 *
 * Results land in `{profileId}/companies/{id}.json`, shared by everyone who
 * works there, with a `{universalName} -> {id}.json` symlink for lookup by
 * vanity slug.
 *
 * Paced with the same random 2–8s delay as the other bulk readers, and metered
 * on its own `company` quota rather than the enrichment one: this reads org
 * pages on a different LinkedIn resource, so resolving employers should never
 * eat the budget for enriching people.
 */

import { type Company, companyId, fetchCompany } from "../linkedin/api/endpoints/companies.js";
import { loadSession } from "../linkedin/api/session.js";
import type { ConnectionsStore, StoredCompany } from "../store/connections-store.js";
import { resolveStorePath, Store } from "../store/index.js";
import { AccountQuota } from "../utils/account-quota.js";
import * as output from "../utils/output.js";
import { describeWait, describeWindow } from "../utils/quota.js";
import {
  DEFAULT_PAGE_DELAY,
  type RandomDelayConfig,
  randomPageSleep,
} from "../utils/random-delay.js";
import { hasSalesNavSeat } from "./connections-of.js";

export interface CompaniesOptions {
  account?: string;
  store?: string;
  json?: boolean;
  force?: boolean;
  limit?: number;
  /** Only resolve employers of people's *current* roles. */
  currentOnly?: boolean;
  /** For tests: skip the inter-fetch delay. */
  noDelay?: boolean;
  delayConfig?: RandomDelayConfig;
}

/** Distinct company URNs referenced by stored connections' positions. */
export async function collectCompanyUrns(
  cstore: ConnectionsStore,
  currentOnly: boolean
): Promise<string[]> {
  const ids = await cstore.listConnectionIds();
  const seen = new Set<string>();
  for (const id of ids) {
    const rec = await cstore.readConnection(id);
    for (const p of rec?.positions ?? []) {
      if (currentOnly && !p.current) continue;
      const cid = p.companyUrn ? companyId(p.companyUrn) : null;
      if (cid) seen.add(cid);
    }
  }
  return [...seen].sort();
}

export function toStored(c: Company): Omit<StoredCompany, "firstSeenAt" | "lastSeenAt"> {
  return {
    id: c.id,
    companyUrn: c.companyUrn,
    name: c.name,
    universalName: c.universalName,
    website: c.website,
    linkedinUrl: c.linkedinUrl,
    tagline: c.tagline,
    description: c.description,
    industries: c.industries,
    staffCount: c.staffCount,
    staffCountRange: c.staffCountRange,
    companyType: c.companyType,
    foundedYear: c.foundedYear,
    specialties: c.specialties,
    headquarters: c.headquarters,
    followerCount: c.followerCount,
    logoUrl: c.logoUrl,
    autoGenerated: c.autoGenerated,
    fetchedAt: new Date().toISOString(),
  };
}

export async function companiesCommand(
  target: string | undefined,
  opts: CompaniesOptions
): Promise<void> {
  const store = new Store({ path: resolveStorePath(opts.store) });
  await store.init();

  let session: Awaited<ReturnType<typeof loadSession>>;
  try {
    session = await loadSession(store, opts.account);
  } catch (err) {
    output.error(String((err as Error).message), 1);
    return;
  }

  const cstore = store.connectionsFor(session.profileId);
  const config = await store.accounts.readConfig(session.profileId);
  const hasSeat = hasSalesNavSeat(session.accountRecord.cookieJar);
  const quota = await AccountQuota.load(store, session.profileId, "company", config, hasSeat);
  const delayConfig = opts.delayConfig ?? DEFAULT_PAGE_DELAY;

  // Single-company mode.
  if (target) {
    if (!(await quota.tryConsume())) {
      output.error(
        `Company lookup limit reached (${describeWindow(quota.window)}). ` +
          `Capacity returns in ${describeWait(quota.status().nextFreeAt)}.`,
        1
      );
      return;
    }
    const company = await fetchCompany(session.apiClient, target);
    if (!company) {
      output.error(`No company found for "${target}".`, 1);
      return;
    }
    await cstore.upsertCompany(toStored(company));
    if (opts.json) output.printData(company);
    else
      output.success(`Resolved ${company.name ?? company.id} — ${company.website ?? "no website"}`);
    return;
  }

  const wanted = await collectCompanyUrns(cstore, opts.currentOnly === true);
  const known = opts.force ? new Set<string>() : new Set(await cstore.listCompanyIds());
  let todo = wanted.filter((id) => !known.has(id));
  if (opts.limit != null) todo = todo.slice(0, opts.limit);

  if (todo.length === 0) {
    output.info(`No companies need resolving (${wanted.length} referenced, ${known.size} stored).`);
    return;
  }

  const before = quota.status();
  output.info(
    `Resolving ${todo.length} companies (${wanted.length} referenced). ` +
      `Quota: ${before.remaining}/${before.max} remaining (${describeWindow(quota.window)}).`
  );

  let done = 0;
  let failed = 0;
  let first = true;
  for (const id of todo) {
    if (!(await quota.tryConsume())) {
      output.info(
        `Stopped early: company lookup limit reached. ` +
          `Capacity returns in ${describeWait(quota.status().nextFreeAt)} — re-run then to continue.`
      );
      break;
    }
    if (!first && !opts.noDelay) await randomPageSleep(delayConfig);
    first = false;
    try {
      const company = await fetchCompany(session.apiClient, id);
      if (!company) {
        failed++;
        continue;
      }
      await cstore.upsertCompany(toStored(company));
      done++;
      if (opts.json) output.printData(company);
      else output.info(`  ${company.name ?? id} — ${company.website ?? "no website"}`);
    } catch {
      // One unreachable company (restricted, deleted, or a 403) must not end
      // a long run; the id simply stays unresolved for the next pass.
      failed++;
    }
  }
  output.success(`Resolved ${done} companies, ${failed} failed.`);
}
