/**
 * Company lookup — resolve a `urn:li:fsd_company:<id>` to the organisation
 * behind it.
 *
 *   GET /voyager/api/organization/companies/<id>
 *   GET /voyager/api/organization/companies?q=universalName&universalName=<slug>
 *
 * Positions carry `companyUrn`, so this closes the loop between a person's
 * work history and the firm itself without guessing at names or domains.
 * The response is the classic (non-dash) shape: an object `data` plus an
 * `included[]` array carrying `Industry` entities the company references.
 *
 * The fields that matter most here are the ones name-matching can never give
 * you reliably: `companyPageUrl` (the real website), `staffCountRange`
 * (headcount band) and the industry list.
 */
import type { LinkedInApiClient } from "../client.js";

const COMPANY_URL = "https://www.linkedin.com/voyager/api/organization/companies";

/** Numeric LinkedIn company id, from `urn:li:fsd_company:<id>` or a bare id. */
export function companyId(urnOrId: string): string | null {
  const m = /(?:^|:)(\d+)\s*$/.exec(urnOrId.trim());
  return m ? (m[1] ?? null) : null;
}

export interface CompanyStaffRange {
  start: number | null;
  end: number | null;
}

export interface CompanyLocation {
  city: string | null;
  country: string | null;
  line1: string | null;
  postalCode: string | null;
  headquarters: boolean;
}

export interface Company {
  /** Numeric id — the join key back to a position's `companyUrn`. */
  id: string;
  companyUrn: string;
  name: string | null;
  /** LinkedIn vanity slug, e.g. `etymonai`. */
  universalName: string | null;
  /** The company's own website — not the LinkedIn page. */
  website: string | null;
  linkedinUrl: string | null;
  tagline: string | null;
  description: string | null;
  industries: string[];
  /** Exact employee count when LinkedIn exposes one. */
  staffCount: number | null;
  /** Banded headcount, e.g. `{start: 2, end: 10}`. */
  staffCountRange: CompanyStaffRange | null;
  companyType: string | null;
  foundedYear: number | null;
  specialties: string[];
  locations: CompanyLocation[];
  headquarters: CompanyLocation | null;
  followerCount: number | null;
  logoUrl: string | null;
  /** True for LinkedIn's machine-created stub pages — weak evidence. */
  autoGenerated: boolean;
}

type Raw = Record<string, unknown>;

function str(v: unknown): string | null {
  return typeof v === "string" && v.length > 0 ? v : null;
}

function num(v: unknown): number | null {
  return typeof v === "number" && Number.isFinite(v) ? v : null;
}

function loc(v: unknown, hq: boolean): CompanyLocation | null {
  const o = v as Raw | null | undefined;
  if (!o) return null;
  const address = (o.address ?? o) as Raw;
  return {
    city: str(address.city),
    country: str(address.country) ?? str(address.geographicArea),
    line1: str(address.line1),
    postalCode: str(address.postalCode),
    headquarters: hq,
  };
}

/** Pick the largest square logo artifact LinkedIn offers. */
function logo(v: unknown): string | null {
  const arts = ((v as Raw | undefined)?.logo as Raw | undefined)?.artifacts;
  if (!Array.isArray(arts)) return null;
  let best: { w: number; seg: string } | null = null;
  for (const a of arts as Raw[]) {
    const w = num(a.width) ?? 0;
    const seg = str(a.fileIdentifyingUrlPathSegment);
    if (seg && (!best || w > best.w)) best = { w, seg };
  }
  return best ? `https://media.licdn.com/dms/image/${best.seg}` : null;
}

export function parseCompany(resp: Raw, id: string): Company | null {
  const d = (resp.data ?? {}) as Raw;
  if (!d || Object.keys(d).length === 0) return null;
  const included = Array.isArray(resp.included) ? (resp.included as Raw[]) : [];

  const industries = included
    .filter((e) => /\.Industry$/.test(String(e.$type ?? "")))
    .map((e) => str(e.localizedName) ?? str(e.name))
    .filter((x): x is string => x !== null);

  const following = included.find((e) => /FollowingInfo$/.test(String(e.$type ?? "")));

  const range = d.staffCountRange as Raw | undefined;
  const founded = d.foundedOn as Raw | undefined;

  const confirmed = Array.isArray(d.confirmedLocations) ? (d.confirmedLocations as Raw[]) : [];
  const locations = confirmed
    .map((l) => loc(l, l.headquarter === true))
    .filter((l): l is CompanyLocation => l !== null);
  const hq = loc(d.headquarter, true) ?? locations.find((l) => l.headquarters) ?? null;

  return {
    id,
    companyUrn: `urn:li:fsd_company:${id}`,
    name: str(d.name),
    universalName: str(d.universalName),
    // `companyPageUrl` is the company's own site; `url` is the LinkedIn page.
    website: str(d.companyPageUrl),
    linkedinUrl: str(d.url),
    tagline: str(d.tagline),
    description: str(d.description),
    industries,
    staffCount: num(d.staffCount),
    staffCountRange: range ? { start: num(range.start), end: num(range.end) } : null,
    companyType: str((d.companyType as Raw | undefined)?.localizedName) ?? str(d.type),
    foundedYear: num(founded?.year),
    specialties: Array.isArray(d.specialities)
      ? (d.specialities as unknown[]).map((s) => str(s)).filter((s): s is string => s !== null)
      : [],
    locations,
    headquarters: hq,
    followerCount: num((following as Raw | undefined)?.followerCount),
    logoUrl: logo(d.logos),
    autoGenerated: d.autoGenerated === true,
  };
}

/**
 * Pull a numeric company id out of a `?q=universalName` lookup.
 *
 * The query resource answers with the company record under `elements` (nested
 * under `data` in the normalized form), carrying an `entityUrn` in one of
 * LinkedIn's several company namespaces — `fsd_company`, `fs_normalized_company`
 * or a bare `company`. The id is all we take: it then goes through the same
 * by-id fetch as every other target, so there is only one response shape to
 * parse a company out of.
 */
export function parseUniversalNameLookup(resp: Raw): string | null {
  const data = (resp.data ?? {}) as Raw;
  const candidates: Raw[] = [];
  for (const bag of [resp.elements, data.elements, resp.included, data.included]) {
    if (Array.isArray(bag)) candidates.push(...(bag as Raw[]));
  }
  // Some decorations answer with the company object directly under `data`.
  if (Object.keys(data).length > 0) candidates.push(data);
  for (const c of candidates) {
    const id = /urn:li:[a-z_]*company:(\d+)/i.exec(str(c.entityUrn) ?? "")?.[1];
    if (id) return id;
  }
  return null;
}

/** LinkedIn vanity slugs are lowercase alphanumerics plus `-`, `_` and `.`. */
const UNIVERSAL_NAME = /^[a-z0-9][a-z0-9\-_.]*$/;

/**
 * Resolve a vanity slug (`marketbridge`) to a numeric company id.
 *
 * Costs one extra request, so it only runs for a target that is neither a URN
 * nor a bare id — `allman companies` with no target always has URNs from stored
 * positions and never reaches this.
 */
async function resolveUniversalName(
  client: LinkedInApiClient,
  slug: string
): Promise<string | null> {
  const universalName = slug.trim().toLowerCase();
  if (!UNIVERSAL_NAME.test(universalName)) return null;
  try {
    const resp = await client.request<Raw>({
      method: "GET",
      url: `${COMPANY_URL}?q=universalName&universalName=${encodeURIComponent(universalName)}`,
    });
    return parseUniversalNameLookup(resp ?? {});
  } catch {
    return null;
  }
}

/** Fetch one company by `urn:li:fsd_company:<id>`, bare numeric id, or vanity slug. */
export async function fetchCompany(
  client: LinkedInApiClient,
  urnOrId: string
): Promise<Company | null> {
  const id = companyId(urnOrId) ?? (await resolveUniversalName(client, urnOrId));
  if (!id) return null;
  const resp = await client.request<Raw>({ method: "GET", url: `${COMPANY_URL}/${id}` });
  return parseCompany(resp ?? {}, id);
}
