import { describe, expect, it } from "vitest";
import { companyId, parseCompany } from "../../src/linkedin/api/endpoints/companies.js";

describe("companyId", () => {
  it("extracts the numeric id from an fsd_company urn", () => {
    expect(companyId("urn:li:fsd_company:99112930")).toBe("99112930");
  });

  it("accepts a bare numeric id", () => {
    expect(companyId("11850")).toBe("11850");
  });

  it("returns null for anything without an id", () => {
    expect(companyId("etymonai")).toBeNull();
    expect(companyId("")).toBeNull();
  });
});

describe("parseCompany", () => {
  // Shaped after a real /organization/companies/<id> response.
  const resp = {
    data: {
      name: "Marketbridge",
      universalName: "marketbridge",
      companyPageUrl: "https://marketbridge.com",
      url: "https://www.linkedin.com/company/marketbridge",
      tagline: "Go-to-Market systems",
      description: "Marketbridge partners with B2B leaders.",
      staffCount: 375,
      staffCountRange: { start: 201, end: 500 },
      companyType: { localizedName: "Privately Held", code: "PRIVATELY_HELD" },
      foundedOn: { year: 1991 },
      specialities: ["ABM/ABX", "Advertising"],
      autoGenerated: false,
      headquarter: {
        city: "Bethesda",
        country: "US",
        line1: "3 Bethesda Metro Center",
        postalCode: "20814",
      },
      logos: {
        logo: {
          artifacts: [
            { width: 100, fileIdentifyingUrlPathSegment: "small.png" },
            { width: 400, fileIdentifyingUrlPathSegment: "large.png" },
          ],
        },
      },
    },
    included: [
      { $type: "com.linkedin.voyager.common.Industry", localizedName: "Advertising Services" },
      { $type: "com.linkedin.voyager.common.FollowingInfo", followerCount: 22580 },
    ],
  };

  it("prefers the company's own site over the LinkedIn page", () => {
    const c = parseCompany(resp, "11850");
    expect(c?.website).toBe("https://marketbridge.com");
    expect(c?.linkedinUrl).toBe("https://www.linkedin.com/company/marketbridge");
  });

  it("captures headcount, both exact and banded", () => {
    const c = parseCompany(resp, "11850");
    expect(c?.staffCount).toBe(375);
    expect(c?.staffCountRange).toEqual({ start: 201, end: 500 });
  });

  it("pulls industry and follower count out of included[]", () => {
    const c = parseCompany(resp, "11850");
    expect(c?.industries).toEqual(["Advertising Services"]);
    expect(c?.followerCount).toBe(22580);
  });

  it("captures type, founding year, specialties and headquarters", () => {
    const c = parseCompany(resp, "11850");
    expect(c?.companyType).toBe("Privately Held");
    expect(c?.foundedYear).toBe(1991);
    expect(c?.specialties).toEqual(["ABM/ABX", "Advertising"]);
    expect(c?.headquarters?.city).toBe("Bethesda");
    expect(c?.headquarters?.headquarters).toBe(true);
  });

  it("picks the largest logo artifact", () => {
    expect(parseCompany(resp, "11850")?.logoUrl).toContain("large.png");
  });

  it("sets the urn from the id and keeps them consistent", () => {
    const c = parseCompany(resp, "11850");
    expect(c?.id).toBe("11850");
    expect(c?.companyUrn).toBe("urn:li:fsd_company:11850");
  });

  it("degrades to nulls rather than throwing on a sparse response", () => {
    const c = parseCompany({ data: { name: "Tiny Co" } }, "1");
    expect(c?.name).toBe("Tiny Co");
    expect(c?.website).toBeNull();
    expect(c?.staffCountRange).toBeNull();
    expect(c?.industries).toEqual([]);
    expect(c?.headquarters).toBeNull();
  });

  it("returns null when the response carries no company", () => {
    expect(parseCompany({}, "1")).toBeNull();
    expect(parseCompany({ data: {} }, "1")).toBeNull();
  });
});
