/**
 * ConnectionsStore company methods.
 * Real temp directory (no git). Synthetic ids.
 */
import { mkdtemp, readlink, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { ConnectionsStore, type StoredCompany } from "@/store/connections-store.js";
import type { StoreGit } from "@/store/git.js";

const NOOP_GIT = {} as unknown as StoreGit;

let accountDir: string;
let cstore: ConnectionsStore;

beforeEach(async () => {
  accountDir = await mkdtemp(join(tmpdir(), "allman-companies-"));
  cstore = new ConnectionsStore(accountDir, NOOP_GIT);
});
afterEach(async () => {
  await rm(accountDir, { recursive: true, force: true });
});

function company(
  over: Partial<StoredCompany> = {}
): Omit<StoredCompany, "firstSeenAt" | "lastSeenAt"> {
  return {
    id: "11850",
    companyUrn: "urn:li:fsd_company:11850",
    name: "Marketbridge",
    universalName: "marketbridge",
    website: "https://marketbridge.com",
    linkedinUrl: null,
    tagline: null,
    description: null,
    industries: ["Advertising Services"],
    staffCount: 375,
    staffCountRange: { start: 201, end: 500 },
    companyType: "Privately Held",
    foundedYear: 1991,
    specialties: [],
    headquarters: null,
    followerCount: null,
    logoUrl: null,
    autoGenerated: false,
    fetchedAt: "2026-01-01T00:00:00.000Z",
    ...over,
  };
}

describe("company store", () => {
  it("round-trips a company and lists its id", async () => {
    await cstore.upsertCompany(company());
    expect(await cstore.listCompanyIds()).toEqual(["11850"]);
    const read = await cstore.readCompany("11850");
    expect(read?.website).toBe("https://marketbridge.com");
    expect(read?.staffCountRange).toEqual({ start: 201, end: 500 });
  });

  it("writes a universalName alias pointing at the id file", async () => {
    await cstore.upsertCompany(company());
    const target = await readlink(join(accountDir, "companies", "marketbridge"));
    expect(target).toContain("11850.json");
  });

  it("never downgrades a known value to null on re-fetch", async () => {
    await cstore.upsertCompany(company());
    // A later, sparser response must not erase the website or headcount.
    await cstore.upsertCompany(company({ website: null, staffCount: null, foundedYear: null }));
    const read = await cstore.readCompany("11850");
    expect(read?.website).toBe("https://marketbridge.com");
    expect(read?.staffCount).toBe(375);
    expect(read?.foundedYear).toBe(1991);
  });

  it("applies real updates and preserves firstSeenAt", async () => {
    await cstore.upsertCompany(company());
    const first = await cstore.readCompany("11850");
    await cstore.upsertCompany(company({ staffCount: 400 }));
    const second = await cstore.readCompany("11850");
    expect(second?.staffCount).toBe(400);
    expect(second?.firstSeenAt).toBe(first?.firstSeenAt);
    expect(second?.lastSeenAt).not.toBe(first?.firstSeenAt);
  });

  it("returns an empty list before anything is stored", async () => {
    expect(await cstore.listCompanyIds()).toEqual([]);
    expect(await cstore.readCompany("nope")).toBeNull();
  });
});
